version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: mern-netflix-clone
    ports:
      - 27017:27017
    volumes:
      - mern-netflix-clone-mongo-dbv:/data/db/
volumes:
  mern-netflix-clone-mongo-dbv:
